libretro/beetle-psx-libretro

libretro.cpp
http://libretro.com/forums/showthread.php?t=4658&p=32147&viewfull=1#post32147
=> Add skip bios option, thanks to theelf

Makefile, libretro.cpp, mednafen/psx/gpu.cpp, mednafen/psx/gpu.h
=> Dynamic VRAM allocation and savestate backward compat

README.md
I didn't mention anything about official .pbp files because they're not supported yet.
=> Add info for .m3u and .pbp files

libretro.cpp
and add a couple more options for finer control.
=> Move crop overscan to a core option

Makefile
All this ARM stuff is set by default by the toolchain.
=> Cleanup Makefile, remove armv, it should be fit inside unix.

libretro.cpp
Exceptions are now caught while attempting to load content. If one occurs, then an error log message is printed out and control comes back to the frontend.
=> All exceptions are now caught within retro_load_game

Makefile
=> Fix Emscripten build

README.md
=> Small typo fix on README.md

pgxp/pgxp_gpu.c
=> Clear upper 5 bits of X and Y coordinates

Makefile, Makefile.common, libretro-common/rthreads/rthreads.c, libretro-common/rthreads/wiiu_pthread.h
this will let it at least boot up games though they will run very slowly.
=> (WiiU) added thread wrapper to make it compilable

libretro.cpp, mednafen/mempatcher.cpp, mednafen/settings.cpp
Thrown together in an hour.  Likely incomplete, but at least it works with simple single-line codes.  Some code was copy and pasted from mednafen's source code, and adapted for this fork.  Feel free to fix what's broken, or let me know what's wrong so I can fix it.
=> Enable Cheat Support

libretro.cpp, rsx/rsx_lib_gl.cpp, rustation-libretro/src/shaders/command_fragment.glsl.h, rustation-libretro/src/shaders/command_vertex.glsl.h
also add xBR, and re-add bilinear and 3point.
=> move SABR texcoord offset caclulations to vertex; should be a little faster

libretro.cpp, rsx/rsx_lib_gl.cpp, rustation-libretro/src/shaders/command_fragment.glsl.h
It's sort of like a sharper/smoother bilinear, so I considered replacing bilinear with it but figured I'd just add it in instead.
=> add jinc2 texture filter

mednafen/cdrom/CDAccess_PBP.cpp, msvc/msvc-2010.sln
If this works as intended it should fix https://github.com/libretro/beetle-psx-libretro/issues/130
=> Try to fix some pbp files not booting

libretro-common/rthreads/rthreads.c, libretro.cpp
- Updated thread library to compile in WinRT
- Fixed bug that left core unusable after unloading a game
=> WinRT and other fixes

Makefile.common, input.cpp, input.h, libretro.cpp
I've isolated the bulk of the input code from out of libretro into new files input.cpp/h.
From this base I've then added mouse support.
=> Mouse Support

input.cpp
Added support for the Guncon / G-Con 45 lightgun from Namco.
Implemented using a combination of the pointer and mouse APIs.
Left mouse: Trigger
Right click / mouse button 4: Gun 'a'
Middle click / mouse button 5: Gun 'b'
=> Guncon / G-Con 45 support

libretro.cpp
I just ran into the problem mentioned in #184, and this is my stab at fixing it.
With this change, I can see the log messages adjusting the PBP image offset when loading savestates, which I didn't before. And I tested it by loading a Disc 2 savestate, and by restarting after loading the savestate and loading a Disc 2 save file. Both seemed to work.
There's only a few relevant lines, but I unfortunately had to move the function below the CDInsert / Eject functions, so it looks like there's more. 
I'm brand new to libretro, and rusty at C++, so I'd appreciate any feedback or suggestions!
=> Fix save state loading with multi-disc PBPs

.gitignore, Makefile, Makefile.common, deps/flac-1.3.2/src/libFLAC/windows_unicode_filenames.c, deps/libchdr/chd.c, deps/libchdr/coretypes.h, deps/lzma-16.04/C/CpuArch.c, libretro-common/include/streams/file_stream_transforms.h, libretro-common/streams/file_stream_transforms.c
I noticed Appveyor builds for everything are failing, but it seems to be an issue on Appveyor's end - I will try to contact them and get it sorted.
=> Enabled CHD support for MSVC and UWP

libretro.cpp, libretro_cbs.c, libretro_cbs.h, parallel-psx/renderer/renderer.cpp
I played with a few different strategies and minimized the init_pipelines() calls in different commits, but there's no need to keep those separate in the git history.
=> [squash and merge] runtime update for vulkan texture filtures

Makefile
=> Fixed Makefile for Vulkan

parallel-psx/renderer/renderer.cpp
Fallback to 8x shader instead of 2x.
=> "Fix" resolver shader with 16x IR.

rsx/rsx_lib_vulkan.cpp
Looks better as we don't have a 16x16 block resolver yet.
=> Clamp IR factor to 8 with SSAA.

mednafen/cdrom/CDAccess_Image.cpp, msvc/mednafen_psx_hw_libretro.vcxproj, msvc/mednafen_psx_hw_libretro.vcxproj.filters, msvc/mednafen_psx_libretro.vcxproj, msvc/mednafen_psx_libretro.vcxproj.filters
This seems to be enough to build both the non-HW and HW version for me
=> MSVC2017 build fixes

libretro.cpp, mednafen/psx/cdc.cpp, mednafen/psx/cdc.h, mednafen/psx/dis.cpp, mednafen/psx/gpu_common.h
Reverts libretro/beetle-psx-libretro#504
=> Revert "Cherrypick changes done between versions 1.21.3 and 1.22.2"

rsx/rsx_intf.cpp
Two feature commits in this PR to cut down on the number of PRs I've been throwing out lately.
Implements horizontal overscan cropping feature and initial/last scanline feature. Unlike the software core, the initial/last scanline don't require restarting the core to take effect, which is pretty nice.
=> Implement crop overscan and initial/last scanline options for GL renderer

libretro.cpp, parallel-psx/renderer/renderer.cpp, parallel-psx/renderer/renderer.hpp, rsx/rsx_intf.cpp
Implements initial/last scanline core options for Vulkan renderer and unhides them.
=> Implement initial/last scanline options for Vulkan

rsx/rsx_intf.cpp
This issue has a bit of an odd history. For some period of time before October, the core was forcing Vulkan for the hardware renderer even if the frontend driver was set to OpenGL. After Rinnegatamante's changes in October, the core was still forcing Vulkan, but now *only if* the frontend requested context wasn't OpenGL. That meant setting the D3D9, D3D10, etc. drivers in RetroArch would still cause the core to force Vulkan if possible when the actual desired behavior is for the core to fall back to the software renderer. Additionally, if RETRO_ENVIRONMENT_GET_PREFERRED_HW_RENDER was not supported by the frontend, the core would force Vulkan, and only attempt Vulkan, no matter what.
This PR cleans this up by doing a number of things.
1. If the frontend supports …
=> Fix GET_PREFERRED_HW_RENDER handling and fallback

libretro.cpp
It turns out that the internal state variable `PBP_DiscCount` is set to zero when loading single-disk PBP content. This breaks the disk control interface, since the core behaves as though no disks are available - disk 'swapping' therefore behaves unexpectedly, and the frontend will always report a failure when trying to restore the last used disk.
This trivial PR fixes the issue.
=> Fix disk control interface when running single-disk PBP content

rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
Other part of https://github.com/libretro/RetroArch/issues/10677
=> sanitize gl context requests

libretro.cpp
=> Fix alternate bios name loading, better mmap errors

rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
Reverts libretro/beetle-psx-libretro#660
=> Revert "sanitize gl context requests"

libretro_core_options.h, parallel-psx/renderer/renderer.cpp, parallel-psx/renderer/renderer.hpp, rsx/rsx_lib_vulkan.cpp
to hopefully stop crashing other games
=> added track textures option

parallel-psx/custom-textures/texture_tracker.cpp
Fixes the rayman crash when track textures is enabled.
=> Fix failed assert when asked to clear an empty rect

parallel-psx/glsl/primitive.frag, parallel-psx/glsl/vram.h
Fixes for issues highlighted in the attached "before" and "after" images.
=> Fixes for filtered texture rendering

parallel-psx/renderer/renderer.cpp
=> Wrap around in vram on scanout

Makefile.common, mednafen/psx/gpu_polygon.cpp, mednafen/psx/gpu_polygon_sub.cpp
For #714
Note: I only tested this in Vulkan renderer,
Software with scaling is still garbled it seems..
=> Fix Wild Arms 2 overworld forest sprite; some rearranging of code;

mednafen/psx/gpu_polygon.cpp
Should make the code more correct in case of future needs. overall still looks quite hacky though :o
=> Copy adjusted vert for first vert in quad

parallel-psx/atlas/atlas.cpp
Fix #736 
Many thanks to @bslenul for the report. Totally missed this otherwise.
=> Fix "almost" infinite loop in Suikoden

rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
preparatory patch for https://github.com/libretro/RetroArch/pull/11368
=> improve context switching

mednafen/psx/gpu.h, mednafen/psx/gpu_polygon_sub.cpp
For #746
I was hoping this code wouldn't cause problems like this but apparently it does. (Valkyrie Profile is just kind of hard to get right, maybe I'll try a different approach in the future but causing glitches in other games as pointed out is just unacceptable)
Removing the offending code is better than reverting the various related commits I suppose.
Apologies in advance and thanks to @bslenul for the bisect.
=> Remove code from previous changes causing problems in Grandia

mednafen/psx/cdc.cpp
=> Revert "Backport this from mainline (mednafen 1.22.2) -"

beetle_psx_globals.c, beetle_psx_globals.h, libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, mednafen/psx/gte.cpp, rsx/rsx_intf.cpp, rsx/rsx_intf.h, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
=> Fix #256 (Widescreen hack aspect ratio setting)

libretro_core_options.h
@IlDucci please review this, okay?
=> Core options text adjustments

libretro.cpp
Follow up to #830, no need to restart the core anymore.
=> Change crosshair color on-the-fly

mednafen/psx/gpu.cpp, parallel-psx/renderer/renderer.cpp, rsx/rsx_lib_gl.cpp
Fixes https://github.com/libretro/beetle-psx-libretro/issues/835
Also applied it to the hardware renderers for consistency.
=> [Dynamic Cropping] Prevent crashing when having too many lines

libretro.cpp, mednafen/psx/cdc.h
2 LEDs included:
- Main power
- CD access
=> Add libretro LED interface

jni/Android.mk
=> fix 32-bit android buildbot HW builds

intl/crowdin.yaml, libretro_core_options_intl.h
It seems like Crowdin changed the way it's CLI app interpretes the file paths in it's config file, namely relative to the file's location instead of the working directory.
This, naturally, broke the translation synch.
This PR should fix the workflow.
=> Fix Crowdin config & update translations

libretro-common/cdrom/cdrom.c, libretro-common/compat/compat_strl.c, libretro-common/file/file_path.c, libretro-common/glsm/glsm.c, libretro-common/include/file/file_path.h, libretro-common/include/glsm/glsm.h, libretro-common/include/libretro.h, libretro-common/include/lists/dir_list.h, libretro-common/include/retro_common_api.h, libretro-common/include/retro_miscellaneous.h, libretro-common/include/retro_timers.h, libretro-common/include/string/stdstring.h, libretro-common/lists/dir_list.c, libretro-common/lists/string_list.c, libretro-common/rthreads/rthreads.c, libretro-common/string/stdstring.c, libretro-common/vfs/vfs_implementation.c
Reverts libretro/beetle-psx-libretro#901
=> Revert "Updated to current libretro-common"

libretro.cpp
Fixes https://github.com/libretro/beetle-psx-libretro/pull/908#issuecomment-2352034444
=> Fix for Apple OS detection on VM region shifting set.

libretro.cpp, libretro_core_options.h, mednafen/video/Deinterlacer.cpp
Just exposing the built-in option for getting "Bob" available, except with a slight modification to make it actually use low resolution as it should.
=> Add deinterlace method option
