libretro.cpp, mednafen/psx/gpu.cpp, mednafen/psx/gpu.h, mednafen/psx/gpu_common.cpp, mednafen/psx/gpu_line.cpp, mednafen/psx/gpu_polygon.cpp, mednafen/psx/gpu_sprite.cpp
With these patches it's possible to change the upscaling using a core option. If the frontend supports changing the output max width/height through `RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO` the change takes place immediately.
They also fix the savestates: they're always made at 1x so they will remain compatible regardless of the upscaling setting.
=> Turn upscaling into an option, fix savestates

libretro.cpp
In particular it seems Mingw doesn't have it even though it's supposed to be POSIX.
=> Reimplement  since it's not supported in all libcs

libretro.cpp, mednafen/psx/gpu.cpp, mednafen/psx/gpu.h, mednafen/psx/gpu_polygon.cpp
Depending on the game and shader used different modes give different results.
Note that this changes the default behaviour: so far the dithering pattern was scaled alongside with the internal resolution, now it defaults to "1x" since this is the most accurate setting.
=> Implement several dither modes: 1x, upscaled or disabled

libretro.cpp
[Crop overscan was leaving some images improperly centered](http://libretro.com/forums/showthread.php?t=5867), which was cutting off a few pixels of content on one side and leaving a corresponding number of blank pixels on the other side. This option lets the user scoot the image up to 4 pixels in either direction.
=> Add image offset core option

rustation-libretro/src/renderer/GlRenderer.cpp, rustation-libretro/src/renderer/GlRenderer.h, rustation-libretro/src/renderer/shaders/command_fragment.glsl.h, rustation-libretro/src/renderer/shaders/command_vertex.glsl.h
This should improve the performance of game that use texture window heavily by reducing the number of draw calls. Ridge Racer in particular gets a pretty massive speedup with this patch. Functionally it should be equivalent to the previous version.
=> Make the texture window a vertex attribute instead of using uniforms

mednafen/psx/cpu.cpp, mednafen/psx/gte.cpp
I don't know if these changes will have any effects in games since I suspect them to be corner cases in the emulation but they "fix" the cpu and gte tests that are working in the most recent mednafen version (0.9.38.7) but not in the current core -> http://emulation.gametechwiki.com/index.php/PS1_Tests
To be specific, the basic memory loads and branch&links in cpu and the RTPS and RTPT opcode gte tests were reported to have wrong values in those tests (again, I wouldn't count on these changes to have too much of an effect in normal emulation, if at all).
Other than that there are also mismatches in the cpx tests (which probably require more extensive code updates to mednafens code base) and probably in the gpu but I couldn't test the latter since it took apparently forever to complete the …
=> Update small code pieces to closer match mednafen's code

README.md, libretro.cpp
The current name is very vague IMHO, so the option ends up doing the opposite of expected for those who don't know that the Joypad is selected instead of the DualShock by default.
=> Reword "Dualshock analog toggle" option, clarify instruction

mednafen/psx/gte.cpp
- Clamp precise X and Y values to psx limits (fixes crash in RR Revolution)
- Pass Z value as an unsigned 16-bit int (fixes far values wrapping to negative)
=> GTE integration fixes

mednafen/psx/gte.cpp
Fix the following compilation errors:
```
In file included from mednafen/psx/gte.cpp:24:0:
mednafen/psx/gte.cpp: In function 'void TransformXY(int64_t, float, uint16)':
mednafen/psx/gte.cpp:1076:48: error: 'min' was not declared in this scope
precise_x = max(-0x400, min(precise_x, 0x3ff));
^
./mednafen/../pgxp/pgxp_gte.h:67:30: note: in definition of macro 'max'
^
mednafen/psx/gte.cpp:1076:48: note: suggested alternative:
precise_x = max(-0x400, min(precise_x, 0x3ff));
^
./mednafen/../pgxp/pgxp_gte.h:67:30: note: in definition of macro 'max'
^
In file included from C:/msys64/mingw64/include/c++/6.1.0/bits/char_traits.h:39:0,
from C:/msys64/mingw64/include/c++/6.1.0/string:40,
from mednafen/psx/../git.h:4,
from mednafen/psx/../mednafen.h:12,
from mednafen/psx/psx.h:4,
from …
```
=> Fix compilation on MinGW/GCC

mednafen/psx/gpu.h, mednafen/psx/gpu_polygon.cpp
Should fix stretched textures in games like Spyro.
=> Stop quads with partially bad W components from getting rendered.

libretro.cpp, libretro.h
This updates libretro.h and uses the new serialization quirks API to report variable-sized savestates. This also fixes support for frontends which don't support variable-sized savestates, which at present includes RetroArch. Fixes netplay, probably fixes rewind.
=> Report that serialized states are variable sized

libretro.cpp
This patch just makes set_controller_port ignore ports beyond MAX_PLAYERS.
Fixes a crash with netplay, but also fixes a crash that can be achieved without netplay: Set your max players to at least 9, then try to set the controller on port 9 and mednafen/PSX craps the bed.
=> set_controller_port can try to set a port beyond what we support

libretro.cpp
Reverts https://github.com/libretro/beetle-psx-libretro/commit/76b13e1ccf1f3085fd5e5de21e221e521fb1bf72.
beetle-psx-libretro will segfault regardless, see https://github.com/libretro/RetroArch/issues/4493.
=> Revert 'Better error handling'

libretro.cpp
'+' seems to be a popular divider when it comes to cheats within RetroArch, but any cheat with a + in it would cause mednafen to error out.  I added + to the ignored character list to work around this.  Problem solved for now.
=> Add + to the ingored character list when processing cheats.

rustation-libretro/src/retrogl/retrogl.cpp
The rename was done in 2b2070b, but one file was missed.
Also for some reason fixes the partial screen issue
(https://github.com/libretro/beetle-psx-libretro/issues/136).
I can not tell exactly what caused the issue but it seemed that libretro was getting wrong information about the viewport (the clipping seemed to be on the libretro level).
=> Convert remaining option names to option_* macros.

libretro.cpp, mednafen/mempatcher-driver.h, mednafen/mempatcher.cpp
Codes are delimited based on any non-hexdec character.
Individual codes can be split into two parts [8+4char] or in a single part [12char].
Changes to mempatcher.cpp and mempatcher-driver.h are backported from a newer version of standalone mednafen, with minor tweaks to make it cooperate with this fork.
=> Add multiline cheat support.

rustation-libretro/src/shaders/command_fragment.glsl.h
Those -0.5 texel offsets were added to reduce the artifacting that happens with these filtering methods when they sample outside of the desired texture (both of them sample texels surrounding the current texel and then average their values together; this can lead to grabbing outlines or other colors that are in neighboring textures on the same texture sheet). This does not fix JINC2, which samples 2 texels out. This behavior leads me to guess that Tomb Raider may use a palette texture for the gouraud shading and these algos are jumping into the adjacent palettes when they sample the neighboring texels. /shrug
=> fix splotchy tomb raider skin with bilinear/3point

mednafen/psx/gpu.cpp, rsx/rsx_intf.cpp, rsx/rsx_intf.h, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
In this PR, the GL renderer imitates the vulkan renderer's behavior in regards to tracking the behavior of mednafen's MaskEvalAND and MaskSetOR variables.
=> Changes to the rsx interface and the gl renderer

mednafen/psx/gpu_polygon.cpp, mednafen/psx/gpu_sprite.cpp
Silences extremely spammy `-Wunused-but-set-variable` warnings when built without `HAVE_OPENGL=1` or `HAVE_VULKAN=1`.
Example:
```
mednafen/psx/gpu_sprite.cpp:178:24: warning: variable 'blend_mode' set but not used [-Wunused-but-set-variable]
mednafen/psx/gpu_sprite.cpp: In instantiation of 'void Command_DrawSprite(PS_GPU*, const uint32_t*) [with unsigned char raw_size = 1u; bool textured = true; int BlendMode = 0; bool TexMult = true; unsigned int TexMode_TA = 2u; bool MaskEval_TA = true; uint32_t = unsigned int]':
mednafen/psx/gpu.cpp:498:1:   required from here
mednafen/psx/gpu_sprite.cpp:178:24: warning: variable 'blend_mode' set but not used [-Wunused-but-set-variable]
mednafen/psx/gpu_sprite.cpp: In instantiation of 'void Command_DrawSprite(PS_GPU*, const uint32_t*) [with unsigned …
```
=> Silence -Wunused-but-set-variable warnings

libretro.cpp
Mednafen has functionality to load a playstation executable ([like this](http://psx.amidog.se/doku.php?id=psx:download:cpu#CPU_Test))  instead of an cd.
In Beetle this functionality is implemented but a bug caused the executable to not load.
After a simple patch the functionality now works.
=> Fix Playstation executable loading.

Makefile
`-lpthread` is a linker flag and should not be in `FLAGS` and only in `LDFLAGS`.  This silences the following numerous warnings on freebsd.
```
cc: warning: -lpthread: 'linker' input unused
```
It might be a good idea to do this for other platforms too, but I am reluctant to make changes for something I can't test.
=> Silence linker unused warnings

mednafen/cdrom/CDAccess_CHD.cpp, mednafen/cdrom/CDAccess_CHD.h
Decompressing an entire chd file is obnoxiously slow, but this matches the behavior for bin/cue where the entire image is read into memory when opened.
=> cdrom: respect disc cache setting for chd files

deps/libchdr/chd.c, deps/libchdr/chd.h, mednafen/cdrom/CDAccess_CHD.cpp, mednafen/cdrom/CDAccess_CHD.h
This makes the cache disc option more tolerable than my previous attempt.  Loading multi-disc playlists with a cold OS page cache still produces mystifying delays on startup, but at least it doesn't peg a CPU to 100% for over a minute.
I'm still dissatisfied with pre-caching discs to avoid stutter.  You shouldn't need an SSD to be able to keep up with a simulated 2x CD-ROM drive from 1994.  The CD emulation code probably needs to be reworked.
=> Precache compressed (rather than uncompressed) CHD data

mednafen/cdrom/CDAccess.cpp, mednafen/cdrom/CDAccess.h, mednafen/cdrom/CDAccess_CHD.cpp, mednafen/cdrom/CDAccess_CHD.h, mednafen/cdrom/CDAccess_Image.cpp, mednafen/cdrom/CDAccess_Image.h, mednafen/cdrom/CDAccess_PBP.cpp, mednafen/cdrom/CDAccess_PBP.h, mednafen/cdrom/cdromif.cpp, mednafen/cdrom/cdromif.h, mednafen/psx/cdc.cpp
This avoids needing to turn on CD pre-caching to prevent emulation stuttering.  The two changes are fairly simple:
- Instead of synchronously waiting for the background I/O thread and blocking emulation, make the emulated program wait longer and check back later.  This seems unlikely to cause compatibility problems given that real games had to contend with imperfect physical CD-ROM drives -- some of which were being literally melted by the power supply -- but the pre-cache option is available to bypass this if needed.
- Annoyingly, there is `PreSeekHack` method which synchronously reads subchannel data *prior* to emulating the seek time.  Since the CD interface actually reads the entire sector to extract the subchannel data, this defeats many of the benefits of background I/O (speculative …
=> Avoid stuttering on CD-ROM sector reads

mednafen/cdrom/CDAccess_PBP.cpp
This fixes a compiler error I received when trying to build for Android arm-v7a. It also looks like the error could lead to a segfault.
Error was:
```
mednafen/cdrom/CDAccess_PBP.cpp:675:79: error:
cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic function; call will abort at
runtime [-Wnon-pod-varargs]
log_cb(RETRO_LOG_WARN, "[PBP] Invalid path/filename for SBI file %s\n", sbi_path);
```
=> Fix compilation on Android

input.cpp, libretro-common/include/libretro.h
Added support for the Namco "neGcon" controller. It's an unusual peripheral with a twisting middle, two analog face buttons and a left (only) analog trigger. 
* I've mapped the twist action to the left analog stick x-axis.
* Analog button I is mapped to RetroPad controls R2 and B
* Analog button II is mapped to RetroPad controls L2 and Y
* Analog left shoulder is mapped to RetroPad control L1.
The three analog buttons are implemented with support for the new libretro analog buttons API. This means that if the user binds an analog axis to the input, the analog value can be read by the core and give you a smooth input. e.g. you can play Gran Turismo like a modern racer using your Xbox 360 triggers for accelerate and brake.
=> Namco "neGcon" support

input.cpp
Use a better x-scaling for both lightgun types, based on empirical evidence.
Thanks to @retro-wertz for suggesting I revisit this.
=> More accurate lightgun x-scaling

libretro.cpp
There was a comment on https://github.com/libretro/beetle-psx-libretro/pull/266 about one of the SetDisc calls being redundant. We need the one in `CDInsertEject`, but I removed the other one. I still see the correct log messages, and the state seems to load properly and I can load disc 2 savegames after a soft reset.
=> Remove a redundant SetDisc call when loading multi-disc PBP files

README.md
This hopefully will alleviate any confusion for users who are told to set "CD Image Cache" to "On" to fix a Vulkan/X server related bug.
=> s/CD Image Cache/CD Access Method/

mednafen/mempatcher.cpp
Using the wrong conversion specifier is undefined behavior. `p` should be used for pointers. Not that big of a deal, but undefined behavior is still undefined behavior.
=> Use correct conversion specifier

libretro.cpp
The line was duplicated/long. Combined with the two ternary operators in the same call makes it hard to read. This minor patch should ease maintainability.
=> Refactor SetDisc calls into function

libretro.cpp
should probably fix this issue, assuming that he is using single-disc game.
https://github.com/libretro/beetle-psx-libretro/issues/297
When a game is only using 1 disk to play, loading state will deduct -1 from CD_SelectedDisc which will make this < 0 causing emulation to stop during disk access.
This PR will check how many discs are there (PBP_DiscCount) and only deducts CD_SelectedDisc when its greater than 0(multiple-disc game).
=> PBP: CD_SelectedDisc cannot be < 0

libretro-common/vfs/vfs_implementation.c
I just copied the entire file from RetroArch repo's libretro-common.
=> update vfs_implementation to use 64-bit ftell() in Windows

parallel-psx/renderer/renderer.cpp
Increase Z increment for primitives.
- Fixes Z-fighting when drawing with multi-pass blending with W (passes were too close).
=>  Solve issue #303: Silent hill glitches with pgxp

libretro-common/glsm/glsm.c
There isn't a 3.1 core profile context and requesting one is wrong. Recent mesa commits have revealed this as wrong and causes problems for beetle-psx. A 3.3 OpenGL context is what beetle-psx originally requested, but at some point this was lowered.
Fixes https://github.com/libretro/beetle-psx-libretro/issues/315
=> libretro-common: Bump OpenGL version requirement to 3.3

README.md
Looks like the OpenGL requirements got bumped up from 3.2 to 3.3
=> Update README.md: Change OpenGL 3.2 to 3.3

libretro-common/rthreads/rthreads.c
There is no 'BSD' define anywhere in the Makefiles, so change the check to built-in platform defines.
=> Fix BSD build

deps/flac-1.3.2/src/libFLAC/windows_unicode_filenames.c, libretro.cpp, mednafen/mednafen-types.h, mednafen/psx/cpu.h, mednafen/psx/gpu_common.h, mednafen/psx/mdec.cpp, mednafen/psx/timer.cpp, mednafen/psx/timer.h, parallel-psx/atlas/atlas.hpp, parallel-psx/vulkan/command_buffer.hpp, parallel-psx/vulkan/image.hpp, parallel-psx/vulkan/shader.cpp, parallel-psx/vulkan/util.hpp, parallel-psx/vulkan/vulkan.hpp, rsx/shaders_gl/command_fragment.glsl.h, rsx/shaders_gl/command_vertex.glsl.h, rsx/shaders_gl/shaders_common.h
Fixes to source code to compile on MSVC 2017.  These changes were also tested on mingw64, and still built okay.  Have not tested the impact on CLANG builds or other compilers.
* `MDFN_ALIGN` is defined for MSVC now as `__declspec(align(n))`
* `MDFN_ALIGN` moved to beginning of variable declaration, as needed by `__declspec(align(n))`
* `NO_INLINE` moved to before the type of the function, as needed by `__declspec(noinline)`
* `MDFN_FASTCALL` moved to between function type and function name, as needed by `__fastcall`
* Fixed libflac bug where it did not return the handle value
* Suppressed a compiler error in `GetTexel` by assigning an uninitialized variable to NULL.  An invalid `TexMode_TA` value will now segfault from a NULL pointer instead of using some random memory.
* Suppressed a …
=> Fixes to code to compile on MSVC 2017

Makefile, deps/flac-1.3.2/src/libFLAC/windows_unicode_filenames.c, libretro.cpp, mednafen/mednafen-types.h, mednafen/psx/cpu.h, mednafen/psx/gpu_common.h, mednafen/psx/mdec.cpp, mednafen/psx/timer.cpp, mednafen/psx/timer.h, parallel-psx/atlas/atlas.hpp, parallel-psx/vulkan/command_buffer.hpp, parallel-psx/vulkan/image.hpp, parallel-psx/vulkan/shader.cpp, parallel-psx/vulkan/util.hpp, parallel-psx/vulkan/vulkan.hpp, rsx/shaders_gl/command_fragment.glsl.h, rsx/shaders_gl/command_vertex.glsl.h, rsx/shaders_gl/shaders_common.h
Fixes to source code to compile on MSVC 2017, plus changes to the makefile which might fix it.  These changes were also tested on mingw64, and still built okay.  Have not tested the impact on CLANG builds or other compilers.
I'm just making this pull request to see if the tests pass.
* `MDFN_ALIGN` is defined for MSVC now as `__declspec(align(n))`
* `MDFN_ALIGN` moved to beginning of variable declaration, as needed by `__declspec(align(n))`
* `NO_INLINE` moved to before the type of the function, as needed by `__declspec(noinline)`
* `MDFN_FASTCALL` moved to between function type and function name, as needed by `__fastcall`
* Fixed libflac bug where it did not return the handle value
* Suppressed a compiler error in `GetTexel` by assigning an uninitialized variable to NULL.  An invalid …
=> Fixes to code to compile for MSVC + changes to makefile

Makefile, deps/flac-1.3.2/src/libFLAC/windows_unicode_filenames.c, libretro.cpp, mednafen/mednafen-types.h, mednafen/psx/cpu.h, mednafen/psx/gpu_common.h, mednafen/psx/mdec.cpp, mednafen/psx/timer.cpp, mednafen/psx/timer.h, msvc/mednafen_psx_hw_libretro.sln, msvc/mednafen_psx_hw_libretro.vcxproj, msvc/mednafen_psx_hw_libretro.vcxproj.filters, msvc/mednafen_psx_libretro.sln, msvc/mednafen_psx_libretro.vcxproj, msvc/mednafen_psx_libretro.vcxproj.filters, parallel-psx/atlas/atlas.hpp, parallel-psx/vulkan/command_buffer.hpp, parallel-psx/vulkan/image.hpp, parallel-psx/vulkan/shader.cpp, parallel-psx/vulkan/util.hpp, parallel-psx/vulkan/vulkan.hpp, rsx/shaders_gl/command_fragment.glsl.h, rsx/shaders_gl/command_vertex.glsl.h, rsx/shaders_gl/shaders_common.h
Fixes to source code to compile on MSVC 2017, plus changes to the makefile to compile on MSVC 2017, plus additional Project files for the HW and SW rendering versions of the program.
These changes were also tested on mingw64, and still built okay.  Have not tested the impact on CLANG builds or other compilers.
* `MDFN_ALIGN` is defined for MSVC now as `__declspec(align(n))`
* `MDFN_ALIGN` moved to beginning of variable declaration, as needed by `__declspec(align(n))`
* `NO_INLINE` moved to before the type of the function, as needed by `__declspec(noinline)`
* `MDFN_FASTCALL` moved to between function type and function name, as needed by `__fastcall`
* Fixed libflac bug where it did not return the handle value
* Suppressed a compiler error in `GetTexel` by assigning an uninitialized …
=> Fixes to code to compile for MSVC + changes to makefile + projects

libretro.cpp, mednafen/state.cpp
* Savestate Performance Fix - no longer does giant memory allocations and copies
* Loadstate Performance Fix - no longer does N^2 string comparisons
* Fast Savestates (excludes text labels from the savestates, 20% speedup)
* Minor Savestate Performance Fix, no longer uses snprintf when strncpy will do.  Only applies to the text labels, no effect on fast savestates.
=> Performance Fixes for Savestates + Fast Savestates

Makefile
UWP does not support OpenGL, do not link against opengl32.lib in that case
=> Fix UWP build

Makefile
This reverts commit 3eac43eeef117c93139536873beb124a903ecb44, reversing
changes made to 4a75947e0f979c10ab0337d9bbd7b4f485674537.
@claudiuslollarius It seems this was falsely detecting our buildbot builds as UWP and thus failing to link GL on them, as well, since we're building it with MSVC2017. Got any other ideas to differentiate?
=> Revert "Merge pull request #335 from Aftnet/master"

Makefile
Trying to fix this again, hopefully without spillover this time.
UWP has no opengl32.lib and the software renderer does not require it anyways.
I am removing `LDFLAGS += opengl32.lib` if and only if `windows_msvc2017_uwp` is specified as part of the platform. This should not affect anything but
a. UWP builds
b. Visual Studio builds (see enclosing `ifneq (,$(findstring windows_msvc2017,$(platform)))` block
=> Fixing UWP build

pgxp/pgxp_gpu.c, rsx/rsx_lib_gl.cpp, rsx/shaders_gl/command_fragment.glsl.h, rsx/shaders_gl/command_vertex.glsl.h
- Clamp texture coordinates to avoid sampling incorrect values when using filtering options
(replaces the need to offset texcoords by 1/2 pixel for perspective correction)
- Invalidate w component of cached vertices to selectively disable perspective correction when using them.
=> Fix filtering and vertex cache errors in issue #350 and similar

rsx/rsx_lib_gl.cpp, rsx/shaders_gl/command_fragment.glsl.h
Borrow code from Vulkan implementation to fix incorrect sampling of texels on some sprite edges.
Replaces the UV min/max calculation code too.
=> Fix incorrect sampling on the edge of sprites. Fixes issue #349

rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
Changed the way primitives are stored and the order in which they are drawn. Needed for
proper masking between opaque and semi-transparent primitives.
Probably not 100% correct but seems to fix the fog issue in Silent Hill (Issue #306)
=> Mask bits support using OpenGL stencil buffer

rsx/shaders_gl/command_fragment.glsl.h, rsx/shaders_gl/command_vertex.glsl.h
- Sample 4 nearest texel centres in any direction
- Remove black samples that are fully transparent
- Use filtered samples to discard transparent pixels for smoother edges
=> Improvements to bilinear filtering (should fix issue #374)

input.cpp, input.h, libretro.cpp
This pull request just copies my recent PCSX ReARMed NegCon improvements ([pcsx_rearmed PR #187](https://github.com/libretro/pcsx_rearmed/pull/187)) to the Beetle PSX core.
It adds the same two core options:
- NegCon Twist Response: enables the user to select an analog response appropriate for mapping the NegCon twist action to standard gamepads. The choices are 'linear', 'quadratic' and 'cubic'.
- NegCon Twist Deadzone: allows the user to properly account for analog drift when a non-linear analog twist response is selected.
=> Refine NegCon Controls

parallel-psx/renderer/renderer.cpp
It was keeping pre-rendered backgrounds and some menus from updating with the new texture filters.
=> removed state.textured conditional

mednafen/tremor/block.c
Hi all,
There is a possible null pointer deference issue found by Qihoo360 CodeSafe Team.
Details as bellow:
in line 240, the condition expression, pointer 'vi' may be a null pointer.
in line 245 (246 repaired), directly deference it as the condition of 'for' statement, which may cause null pointer deference.
Cheers
Qihoo360 CodeSafe Team
=> add checking against NULL

libretro.cpp, mednafen/cdrom/CDAccess_Image.cpp
Prevents the following crash when a cue sheet references a non-existant file:
```
Microsoft Visual C++ Runtime Library
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
```
Attempt to read LBA 16, >= LBA 0
CDIF Raw Read error
terminate called after throwing an instance of 'MDFN_Error'
```
=> Prevent crash when cue sheet references a non-existant file

mednafen/psx/cpu.cpp
Add PGXP calls for instructions that were previously missed. Should improve support for games like Croc, MGS, Alundra 2 and others that rely on CPU instructions for vertex handling.
=> Fix PGXP "+CPU" integration

parallel-psx/vulkan/semaphore.hpp
Warning: Please review and test this, I am not sure that its correct, only that it boots games with amdgpu and vulkan now.
```
Vulkan error at parallel-psx/vulkan/semaphore.hpp:40.
terminate called without an active exception
```
=> vulkan: Remove assert.

mednafen/psx/gpu.cpp, mednafen/psx/gpu.h, mednafen/psx/gpu_polygon.cpp
- Should now correctly cull leaves in Silent Hill in hardware renderers
- Further improves visual stability of 3D objects (particularly notable in Tomb Raider and Xenogears where 3D quads regularly align on screen)
=> Fix issue #368 and enhance flipped sprite detection

libretro.cpp
Proposed fix for the crash that happens when loading a fuill audio cd (all tracks are audio, no mixed modes)
Original problem started here (you need to add/fix recover-raw.h though from a later commit)
https://github.com/libretro/beetle-psx-libretro/commit/3da0bba3d58994d1d46b13e3f4f87dadde3a884d
here's how i came up with this possible fix:
https://github.com/libretro/beetle-psx-libretro/issues/227#issuecomment-456209778
This does cause to generate a few lines like **Attempt to read LBA -5, >= LBA 225249** but not to much that its continous. Only happens when loading audiocd (or probably when track 1 is AUDIO type)
~~One other issue is that with this fix it does directly load AudioCD and go into the cdplayer in the bios, but the framerate there is unstable causing audio problems on …
=> Fix crash when loading Audio CD

input.cpp, libretro.cpp
Call RETRO_ENVIRONMENT_SET_CONTROLLER_INFO to let the front-end know how many ports are supported when multi-tap settings are changed.
Also fix player count with only 1 multi-tap connected.
=> Dynamic controller port count reporting

libretro.cpp, mednafen/psx/cdc.cpp, mednafen/psx/cdc.h, mednafen/psx/dis.cpp, mednafen/psx/gpu_common.h
What needs to be tested before merging:
What games need to be confirmed to be working:
Games which should have music working and not hang anymore:
Games which should not hang anymore:
It would somewhat address the request of issue #487, only in terms of game compatibility.
____
@ofry @Papermanzero @saftle @twinaphex 
Hey people, I need help testing these changes. I've attached below a win64 build for those who can't clone/compile this.
[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/3175558/mednafen_psx_hw_libretro.zip)
=> Cherrypick changes done between versions 1.21.3 and 1.22.2

libretro.cpp, libretro_core_options.h, rsx/rsx_intf.cpp
This PR removes the hardware-specific core options `Renderer (restart)` and `Software framebuffer` from the non-hardware build (since they serve no purpose for the non-hardware build)
This fixes the display of core options when running the non-hardware build using frontends that require the old v0 core options API.
=> Remove HW-specific core options from SW build

libretro-common/include/libretro.h, libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, libretro_options.h
This PR makes the following changes to the core options:
- Update `libretro_core_options` to v1.3 format
- Complete overhaul of option sublabels
- Irrelevant options are now hidden automatically depending upon current renderer
- General tidy up of everything :)
=> Update core options

libretro_core_options.h
This PR fixes a silly typo in the `Widescreen Mode Hack` option sublabel (`ration` -> `ratio`)
=> (Core Options) Fix sublabel typo

libretro.cpp, libretro_core_options.h
This PR does the following:
1. Updates a few core option sublabels to be more descriptive, such as certain options not working with the hardware renderer at the moment
2. Removes some erroneous information regarding horizontal overscan cropping and rewrites that option sublabel
3. Fixes and clarifies overscan cropping comment in libretro.cpp (hopefully to aid in fixing a crop_overscan alignment issue; I'll open an issue for this when I have some more specifics I can point to)
Will follow up by updating the core's libretro doc page with pictures and better descriptions and open an issue for the aforementioned crop_overscan option in the near future.
=> Update core options sublabels

libretro.cpp
Reverts swapped dithering behavior in software renderer introduced by ae09b52 and b0022b1. Fixes #541.
=> Fix swapped dithering (native/upscaled) in sw renderer

libretro.cpp
Fixes issue #543.
The 400px -> 366px crop is for the 368px display mode. Some 368px width games are a little finicky to deal with -- sometimes using 368px results in undercropping while sometimes using 364px results in overcropping. 366px was chosen as a compromise and it seems to work for the most part. Left a comment in the code in case this needs to be adjusted later.
=> Adjust outdated overscan cropping code

Makefile
Haiku doesn't have -ldl but -lroot replaces it
=> Fix Haiku build

libretro.cpp
Reverts 236c81f
When `Crop Overscan` option is enabled, the software renderer tries to also automatically remove vertical overscan from PAL content, which it doesn't try to do for NTSC content. This automatic removal works kind of decently sometimes ([before crop](https://user-images.githubusercontent.com/45282415/67516084-d9024080-f654-11e9-9c77-f326f025e3d0.png), [after crop](https://user-images.githubusercontent.com/45282415/67516090-dacc0400-f654-11e9-970c-3a89ba1b2919.png)) but can also give really poor results other times ([before crop](https://user-images.githubusercontent.com/45282415/67516253-35656000-f655-11e9-97bc-67588b247411.png), [after crop](https://user-images.githubusercontent.com/45282415/67516260-37c7ba00-f655-11e9-87ed-ff5eea8d0ee7.png) - note the miscentered vertical …
=> Remove conflicting PAL overscan crop code in SW renderer

mednafen/psx/gpu.cpp, rsx/rsx_dump.cpp, rsx/rsx_dump.h, rsx/rsx_intf.cpp, rsx/rsx_intf.h
PR implements height padding for GL renderer. This fixes display height for games that don't draw to a full 240 lines framebuffer on original hardware and rely on what seems to be analog encoding to fill in the rest of the lines. Related to issue #525 though this PR only fixes it for the GL renderer and not the Vulkan one.
e.g. Wild Arms (draws to 232 height framebuffer)
**GL Renderer Before**: only framebuffer contents are displayed
**GL Renderer After**: properly letterboxed
Some lingering issues with the implementation: ~~loading save states can cause previous pixels to remain in the extra padded height area (might need to always clear the screen in rsx_gl_finalize_frame before calling bind_libretro_framebuffer, I'll test this out soon)~~ fixed and initial/last scanline options not …
=> Implement framebuffer height padding for GL renderer

rsx/rsx_intf.cpp
Fixes #246
Fixes #427 
`GLRenderer_new` method was not setting `has_software_fb`, meaning that regardless of what the option was set to by the user, the GL renderer would always start with the software framebuffer off. The software framebuffer would have to be forced on by toggling any core option, causing `retro_refresh_variables` to be called, which has a check for `renderer_software_fb` in it. This PR fixes this issue by making sure `renderer_software_fb` is checked and `has_software_fb` is appropriately set by `GLRenderer_new`.
Also fixes the BIOS screen glitches since it turns out the "Sony Computer Entertainment" text requires software framebuffer to be on.
=> Make sure has_software_fb is set by GLRenderer_new

libretro.cpp, mednafen/psx/gpu.cpp, rsx/rsx_dump.cpp, rsx/rsx_dump.h, rsx/rsx_intf.cpp, rsx/rsx_intf.h
PR does three things:
1. Hides overscan and scanline options currently not respected by each hardware renderer
2. Minor fix to properly handle games that try to display outside of the visible scanline region
3. Brings the GL renderer's **Crop Overscan: Off** to almost the same accuracy level as the Software Renderer's **Crop Overscan: Off** (barring differences related to the sw renderer updating on a scanline granularity versus the hw renderer copying the emulated vram fb as a texture)
Point number three was accomplished by modifying `UpdateDisplayMode()` and by extension `rsx_intf_set_display_mode()` to pass down an enum containing the width mode of the image to the renderer, analogous to how the GP1(08h) command sets a width mode of the image. This gives us a more reliable method for …
=> Gl crop overscan accuracy additions

libretro.cpp, parallel-psx/main.cpp, parallel-psx/renderer/renderer.cpp, parallel-psx/renderer/renderer.hpp, rsx/rsx_intf.cpp
Should be safe to merge, but I'll leave open to feedback for a bit.
There's two issues, one that's newly introduced and one that's a preexisting issue. 
The newly introduced issue is that with Crop Overscan **Off**, if a game tries to scroll itself outside of the maximum displayable horizontal area (e.g. when doing screen adjustment in Tomb Raider II) there's some minor flickering alongside the edge it's scrolling out of, possibly due to some rounding error logic that was already in the hardware renderer code. I'll look into this but it's not a priority as no game should really be displaying that close to the edge unless it's programmed poorly or it's trying to do screen adjustment for poorly calibrated CRTs.
The preexisting issue is that this implementation does not respect the …
=> Implement display range code for Vulkan renderer

input.cpp, input.h, libretro.cpp, libretro_core_options.h, rsx/rsx_intf.cpp
PR has a number of small fixes with some code cleanup that I merged in from rz5's other PR into some other cleanup/reorganizing. Changes have been grouped into distinct commits so they're easy to follow. 
The cleanup merging isn't quite done yet but there's a pretty big change I made with core options reordering so it's probably fair to open up to review for now.
**Core options reordering**
Some notes on options
* Internal Color Depth: SW locks to 16, VK autos based on dithering setting. Color depth and dithering should be put together because they are settings that are toggled in relation to one another (at least for GL).
* Texture Filtering: Possible minor optimization? This option is checked by all renderers in `check_variables` but the variables that are set by it in `libretro_cbs.h` …
=> Options cleanup & various miscellaneous fixes

libretro_core_options.h, mednafen/psx/gpu_polygon.cpp, rsx/README.md
Just some minor stuff. Going to merge this in later if there aren't any concerns.
As discussed with r5 and hizzle a while back, we should allow the line render hack for the non-HW build. This is going to cause a slight performance hit for that build, but if we're allowing internal resolution upscaling we should allow this option as well since they're related.
Lot of core option sublabels rewritten to be less wordy or to rework information that was wrong. Still isn't 100% complete yet, but most of it is finished. There's just some lingering details and the NegCon sections remaining. I'd prefer to pare the information even further and leave most of it in the libretro docs, but that's personal taste. It would mostly be useful for menus like RetroArch's XMB that take a long time to scroll …
=> Minor updates

Makefile.common, beetle_psx_globals.c, beetle_psx_globals.h, input.cpp, libretro.cpp, libretro_cbs.c, libretro_cbs.h, mednafen/psx/frontio.cpp, mednafen/psx/frontio.h, mednafen/psx/gpu.cpp, mednafen/psx/gpu_polygon.cpp, mednafen/psx/input/guncon.cpp, mednafen/psx/input/justifier.cpp, mednafen/psx/psx.h, rsx/rsx_intf.cpp
An attempt to solve #471 and #501.
**2x IR scaling before** (note the halved width on cursor, cursor only displaying every other line, improper horizontal positioning)
**2x IR scaling after**
**Crop Overscan before** (improper horizontal positioning)
**Crop Overscan after**
**PAL before** (improper vertical positioning)
**PAL after**
1. Drawing cursor is still yet to be implemented for hardware renderers. I think lightgun games are only really going to work for the hardware renderers if Software Framebuffer is enabled unless we hook in some hard GPU readbacks like what maister was doing a while ago. Getting the lightgun to work with the hardware renderers in the first place is going to require some re-architecting of how we track global state in the core.
2. Scaling formula not modified …
=> Lightgun Fixes

libretro-common/include/libretro.h, libretro.cpp
This PR adds full support for libretro disk control interface v1. This includes the following enhancements:
- Disk names are now shown when swapping disks via the `Current Disk Index` drop down list
- When loading multi-disk content (M3U playlists or PBP files), the last used disk index is now automatically saved/restored
=> Add disk control interface v1 support

mednafen/psx/gpu.cpp
This increases performance slightly. 
When I tested with dynarec and hardware renderer with software framebuffer disabled, I measured an increase from ~300 fps to ~309 fps in soul blade.
PGXP seems to still work fine when changing the mode at run-time.
=> Don't call PGXP functions in gpu when PGXP is disabled

libretro.cpp, rsx/rsx_intf.cpp, rsx/rsx_intf.h, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
Provides some minor performance increase for titles that don't swap PSX VRAM framebuffers at a full ~50 or ~60 Hz refresh rate.
A consequence of enabling this option is that some FMV and BIOS video bugs (occasional garbled 24-bit/15-bit conversion issue very first frame of FMVs, PS BIOS logo teleporting into the bottom right corner at the end of playing the BIOS) are alleviated, but I think this option really only addresses the symptoms and not the cause, so those issues can't be closed on the tracker yet.
I tried implementing this in the GL renderer as well but was tripping over graphical issues left and right, so any help there would be greatly appreciated.
=> Add frame duping support to RSX Vulkan

libretro.cpp, libretro_core_options.h, rsx/rsx_intf.cpp, rsx/rsx_intf.h
Feature discussed back in #573 that's also been requested by users many times on various channels.
The logic still works the same way as before for the `Hardware` option value, which is renamed `Hardware (Auto)`. If the frontend's preferred driver doesn't have a corresponding hardware renderer, we fall back to the software renderer and notify the user, and if the frontend doesn't have a preferred driver, we go down the list trying to initialize a hardware renderer instance until we get one.
The two new option values, `Hardware (Vulkan)` and `Hardware (OpenGL)` work with pretty much the same logic as the frontend having a preferred driver. We try to open the user's selected hardware renderer, and if we're unable to do so we simply notify the user and fall back to the software renderer. …
=> Add support for forcing hw rendering backend

beetle_psx_globals.c, beetle_psx_globals.h, libretro.cpp, libretro_core_options.h, rsx/rsx_intf.cpp, rsx/rsx_intf.h, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
Beetle PSX has traditionally gotten aspect ratio scaling wrong (see [link](https://forum.fobby.net/index.php?t=msg&&th=1117&goto=3777#msg_3777)). This patch brings proper aspect ratio correction for all the renderers and additionally implements a functional equivalent of mednafen 1.24.0-UNSTABLE's `psx.correct_aspect` option. The upstream mednafen code isn't quite suitable for our purposes, so this implementation uses the rsx interface as a more general solution that covers the hardware renderers as well.
`Corrected` gives the proper aspect ratio scaling while `Uncorrected` is the effective "1:1 PAR" mode.
Some users may not be happy with this new behavior that is more accurate and matches upstream more closely and may prefer the old behavior, so `Force 4:3` is left as a legacy option for …
=> Implement aspect ratio core option (psx.correct_aspect equivalent)

libretro.cpp, libretro_core_options.h, mednafen/psx/gpu.cpp, rsx/rsx_intf.cpp
This is an implementation of the feature request #67 
It adds a core option "pal_video_override" that can be used to hack the video timing of PAL games in order to make them run at 60fps instead of 50. The resolution remains the same. NTSC games will ignore that setting entirely so it shouldn't have any impact for them.
As discussed in the issue many (but not all) PAL ports of NTSC games also have black bars at the top and bottom of the screen. This patch will not remove them. An other patch will be necessary to optionally crop the video output to remove those bars.
=> Added "fast PAL" hack to allow PAL games to play at NTSC framerates

input.cpp
I ran some tests on the real hardware and found that my original estimate was significantly lower than the real thing. A good test case is Parasite Eve because the radius it uses to consider that you're running instead of walking is very large and if you under-calibrate you'll end up walking when you go diagonally.
Beyond that, I wonder if it wouldn't make sense to turn this option on by default.
=> Improve DualShock calibration reference

libretro.cpp, mednafen/cdrom/CDAccess_PBP.cpp, mednafen/mempatcher.cpp, mednafen/psx/cdc.cpp, mednafen/settings.cpp, mednafen/state.cpp, mednafen/video/surface.cpp
Fix all build warnings other than those from libretro-common/ or deps/
Would like feedback on whether these changes make sense and don't break anything, as I just made the minimum changes to fix each warning and only build tested.
=> Cleanup warnings: snprintf truncation, strncpy->memcpy, memset

Makefile
As title says, this allows the core to build (and run) on Solaris 11
=> Allow Solaris 11 build

libretro.cpp, mednafen/cdrom/cdromif.cpp, mednafen/mednafen-driver.h, mednafen/mednafen.h, mednafen/psx/cdc.cpp, mednafen/psx/dma.cpp, mednafen/psx/frontio.cpp, mednafen/psx/input/dualshock.cpp, mednafen/psx/input/guncon.cpp, mednafen/psx/input/memcard.cpp, mednafen/psx/input/mouse.cpp, mednafen/psx/irq.cpp, mednafen/psx/mdec.cpp, mednafen/video.h, rsx/rsx_intf.cpp
This PR adds support for v1 of the core->frontend message interface implemented here: https://github.com/libretro/RetroArch/pull/10679
The main benefits are:
- Reduced log spam. Only important messages are recorded via the logging interface - the rest are just output via the OSD.
- Certain warnings/errors are now reported via regular notifications (pop-up widgets), making them more obvious to the user.
- Internal FPS text is now displayed via the status widget:
=> Add support for frontend message interface v1

Makefile
Following the conversation in #659 I will be removing this option from various Makefiles to allow IllumOS builds again while maintaining Solaris compatibility
=> Maintain Solaris compat + restore IllumOS build

mednafen/state.cpp
At present, the core performs out-of-bounds memory access when reading the chunk 'name' identifier every time a save state is made. This was causing a crash on my system.
This trivial PR fixes the issue.
=> Prevent buffer over-read when saving states

jni/Android.mk, parallel-psx/custom-textures/texture_tracker.hpp
A missing header, which makes me wonder how this compiled on any platform, even though it obviously did. And something in the new code requires rtti.
=> Android: Fix hw compilation

Makefile
This fixes the Haiku build as -lrt is replaced with -lroot and SHM flags are not present in Haiku.
=> Fixes Haiku build with LightRec

Makefile
Opt out of LIGHTREC to enable building for iOS/tvOS per https://github.com/libretro/beetle-psx-libretro/issues/702
=> Update Makefile to fix broken iOS/tvOS build

Makefile
Recovered PR #624 that was closed by a force-push.
Old message below:
-----------
I'm getting QA problems in my sandbox cross-compilation environment that /usr/local/lib is pointing to host libraries.
ERROR: beetle-psx-libretro-1.0+gitrAUTOINC+7210cff299-r100 do_package_qa: QA Issue: beetle-psx-libretro: The compile log indicates that host include and/or library paths were used.
Please check the log '/home/dev/embedded/retro-build-enviroment/build/tmp/work/core2-32-poky-linux/beetle-psx-libretro/1.0+gitrAUTOINC+7210cff299-r100/temp/log.do_compile' for more information. [compile-host-path]
=> Removed library path /usr/local/lib.

parallel-psx/atlas/atlas.cpp, parallel-psx/renderer/renderer.cpp
`scanout_vram_to_texture` and related functions was broken in my previous pr if msaa is enabled. This commit should resolves it.
=> Scaled read

libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, mednafen/psx/gpu_polygon.cpp
I don't really know how to make PGXP less glitchy. This however adds a failsafe if a pgxp coordinate is lacking w component:
If the difference between pgxp x and y components and non-pgxp x and y components are too great, the non-pgxp values are used.
This in effect "hides" some more glaring glitches..
=> "Clamp" pgxp coordinates if lacking w components

mednafen/psx/gpu_polygon_sub.cpp
=> Fix Wild Arms 2 overworld forest sprite for software mode with scaling

mednafen/psx/gpu_polygon.cpp
First vertices of quads were not updated in some circumstances.
=> Correct pgxp 2d tolerance for quads

libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, mednafen/psx/gte.cpp, pgxp/pgxp_gte.c, pgxp/pgxp_gte.h, pgxp/pgxp_main.h
Add option to turn off PGXP's NCLIP implementation. This is a workaround for #490.
Not sure if it's a good idea to add yet another option though this one is in duckstation.
(I spent some time following the suggestion iCB mentioned [here](https://github.com/libretro/beetle-psx-libretro/issues/490#issuecomment-469062488): first a snapshot of the memory is taken when the dma starts then the dma is fed from the snapshot instead of updated ram, could be my implementation being wrong but the game is still locking up in the same place.. So far I've no idea how to workaround this for the widescreen case)
=> Add PGXP NCLIP on off switch

parallel-psx/renderer/renderer.cpp
VRAM wraparound wasn't implemented for adaptive smoothing in #723
This update resolves it.
Please let me know if I miss anything this time.
=> VRAM wraparound for adaptive smoothing and copy_vram_to_cpu_synchronous

libretro.cpp
There are two places where `PGXP_SetModes` is called and I only remembered to change one of them. This PR changes the other one also.
=> Fix PGXP vertex culling option not being set on startup

rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_gl.h
Reverts libretro/beetle-psx-libretro#735
you can't follow user pref here, beetle-psx requires glcore on mesa drivers
=> Revert "improve context switching"

.gitlab-ci.yml
This PR modifies the gitlab-ci file to enable building of both the `Beetle PSX` and `Beetle PSX HW` cores
=> (.gitlab-ci.yml) Enable building of both 'mednafen_psx' and 'mednafen_psx_hw'

libretro.cpp, libretro_core_options.h
Commented the lines preventing beetle to use "shared memory cards" when saving method is set to "libretro".
Edited option description.
Now, when the "libretro save method" option is enabled, only the roght card will use the shared method.
=> Shared memory card support with libtetro method

libretro.cpp
Since these only work with Vulkan.
=> Hide "track/dump/replace textures" core options for Software and OpenGL renderers.

deps/lightrec/interpreter.c
This PR handles an undocumented edge case of division overflow in the DIV instruction in lightrec. Without this patch, guest code will get unexpected results, and may even crash the core on x86, as AmiDog's basic CPU test shows. The PR a [pcsx_rearmed counterpart](https://github.com/libretro/pcsx_rearmed/pull/530).
=> Handle DIV overflow in lightrec

libretro.cpp, libretro_core_options.h
This takes way too long and is unresponsive, so don't actually
pre-cache any physical media when pre-cache is enabled
Fixes #795
=> Disable pre-cache for physical media

libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, mednafen/psx/gte.cpp, rsx/rsx_intf.cpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
These options are intended for mobile devices where aspect ratios wider than 16:9 recently became widespread.
If currently using a 21:9 or 32:9 aspect ratio, the user will have to adjust their settings to get their old aspect ratio back.
This closes https://github.com/libretro/beetle-psx-libretro/issues/806.
=> Add 18:9, 19:9 and 20:9 widescreen aspect ratio options

Makefile.common, lightning-lightrec-include/debug.h
Makes lightrec's messages use the log instead of printing directly to stdout/stderr
=> Override lightrec's debug.h with one that uses log_cb

libretro.cpp, libretro_core_options.h, parallel-psx/renderer/renderer.cpp, parallel-psx/renderer/renderer.hpp, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
This PR makes the "Additional Cropping" option work with not only the software renderer, but also with both the Vulkan and OpenGL renderers.
=> Make "Additional Cropping" option compatible with hardware renderers

libretro_core_options.h, mednafen/psx/gpu.cpp, parallel-psx/renderer/renderer.cpp, rsx/rsx_lib_gl.cpp
In particularly inspired by https://github.com/libretro/beetle-psx-libretro/issues/719, this makes it so the Crop Overscan option dynamically crop and center the screen based on how PCSX-ReArmed and DuckStation deal with it (and especially PAL games, which have varying amount of crop, sometimes even in the same game, which makes manually adjusting the overscan and image offset values painful).
This also makes it that, if Crop Overscan is disabled, it will revert back to the unmodified image, including the varying PAL overscans.
=> Make "Crop Overscan" dynamically crop (and center) the screen

mednafen/psx/gpu.cpp, parallel-psx/renderer/renderer.cpp, rsx/rsx_lib_gl.cpp
This fixes the following issues introduced with https://github.com/libretro/beetle-psx-libretro/pull/819:
- The in-game image for Gunbird and Mobile Light Force (an European release of Gunbird) being shifted to the left.
- Garbage textures being shown on the right side of the screen when shifting the image to the left with the software renderer (hardware renderers didn't have this problem).
=> Fix some issues with the dynamic overscan cropping

beetle_psx_globals.c, beetle_psx_globals.h, libretro.cpp, libretro_core_options.h, libretro_core_options_intl.h, mednafen/psx/gpu.cpp, parallel-psx/renderer/renderer.cpp, parallel-psx/renderer/renderer.hpp, rsx/rsx_intf.cpp, rsx/rsx_intf.h, rsx/rsx_lib_gl.cpp, rsx/rsx_lib_vulkan.cpp
In response to https://github.com/libretro/beetle-psx-libretro/issues/820, this adds back the old, static crop behavior, while retaining the new, dynamic one as an additional selection for the "Crop Overscan" option.
=> Add static crop behavior for "Crop Overscan" alongside dynamic

Makefile
This builds and functions as a core though CPU only. 
I would be interested in if WEBGL could function here, I kind of ran into dependency hell when trying to build it against the frontend, but it already uses glsym_es2 for it's menu rendering IE: 
```
[INFO] [EMSCRIPTEN/EGL]: Dimensions: 800x600
[INFO] [GL]: Found GL context: egl_emscripten
[INFO] [GL]: Detecting screen resolution 800x600.
[INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
[INFO] [GL]: Version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium)).
```
Just giving reason as to why I pulled out the GL settings as it will not work when building against the frontend anyway and might confuse users. 
Regardless this should not hurt to merge, the current fake deps are no longer needed.
=> fix emscripten builds

libretro_core_options.h
- Unified the capitalization of the neGcon peripheral to the original one.
- Rewritten the category sublabels to match RetroArch's style.
- Removed unnecessary spaces between slashes.
=> [Core Options Text] Fixed neGcon capitalization, corrected sublabels

Makefile, jni/Android.mk
fixed the regression in android builds caused by [`3f525d7`](https://github.com/libretro/beetle-psx-libretro/commit/3f525d7d67b7c8f83ca0c951c279abc04decb17f)
=> fix #507 again

libretro.cpp, libretro_core_options.h
In order to show correct category icons:
- Changed "hacks" to "Hacks" 
- Changed "Onscreen Notifications" to "On-Screen Display"
Also some cleanups to reduce compilation warnings.
=> Core option category adjustments

libretro.cpp, libretro_core_options.h, mednafen/psx/input/dualshock.cpp, mednafen/psx/psx.h
As an alternative to #858 I'm proposing a new core option that lets you chose a combo from a predefined list, instead of hardcoding a single one:
I say that in pretty much every PR I make but I'm not a dev and there is maybe a better way to handle that, so feel free to edit the PR or to tell me what to change ;) But from my tests and @Sanaki's, it works perfectly fine!
Closes #699
=> Add multiple combos for the analog toggle

libretro.cpp, libretro_core_options.h, mednafen/psx/input/dualshock.cpp, mednafen/psx/psx.h
Adds a user configurable hold delay for the analog mode combo toggle option.
Configurable from 0-5 seconds.
Also changes the default analog mode combo toggle to `L1 + R1 + Select` to prevent accidentally performing a soft-reset in supported games.
=> Adds configurable hold delay for analog toggle

.gitlab-ci.yml, Makefile, libretro.osx.def, parallel-psx/renderer/renderer.cpp, rsx/rsx_lib_gl.cpp
Vertex attribute binding strides must be aligned to 4 bytes, so says MoltenVK. So we'll create the quad as R32G32_SFLOAT instead of R8G8_SNORM.
Also when running a debug build of the core in a debug build of retroarch in the debugger, the dynamic linker gets very confused about which spirv-cross functions to call. The easiest way to give it a clue is to reduce the exported symbol list.
Also fix the debug build on Apple.
=> Fix Vulkan renderer on Metal.

libretro.cpp, libretro_core_options.h, mednafen/psx/input/dualshock.cpp
Since the previous attempt #893 was half-baked, this time current behavior is not touched. But instead:
- New toggle mode which sets the default state as analog instead of digital
- Cleaned up notifications to not spam duplicates
=> Change DualShock analog toggle combo behavior

libretro.cpp, libretro_core_options.h, rsx/rsx_intf.cpp
Currently if the default dynamic cropping option decides to crop top and bottom, like for example in Crash Team Racing, it is not taken into account when calculating aspect ratio. It only uses the manual scanline positions, which also for reasons unknown will crop the already cropped image even more starting from the cropped state, but I couldn't figure out how to ignore the values up to the point of current dynamic cropping.
Also reordered some core options a bit and moved "GPU Rasterizer Overclock" away from between video crop settings to hacks submenu.
=> Fix dynamic crop aspect ratio

Makefile.common, beetle_psx_griffin.cpp, input.cpp, mednafen/psx/frontio.cpp, mednafen/psx/input/negconrumble.cpp, mednafen/psx/input/negconrumble.h
This PR adds a separate neGcon controller profile with rumble support (a modified DualShock profile with neGcon identification and inputs), which was implemented in SwanStation through https://github.com/libretro/swanstation/commit/83776ae7d3b9221b2746f91af0c2d8d9b0994aa7, and is also available in its upstream counterpart and the MiSTer PSX core.
Main use case for this is that quite a handful of neGcon supported games also support sending rumble commands when in neGcon mode (mainly with third party steering wheels in mind).
=> Implement neGcon controller profile with rumble

libretro.cpp
Previously, without this fix, RetroArch randomly (90% chance) crash on game load.
The root problem was the specific virtual address mmap handling on Mach kernel specially on arm64 processors (M1/M2/M3) causes mmap to throw an SIGBUS process exception.
Sorry for my bad english :)
With this fix game loading stable.
=> Fix computing Lightrec base address for macOS.

libretro.cpp, mednafen/cdrom/CDAccess.cpp
Same with the Saturn core, as in allow for example `.hidden-chd` in M3Us.
=> Use less strict extension matching

libretro.cpp, mednafen/video/Deinterlacer.cpp
Tekken wasn't triggering `currently_interlaced`, and also improved bob line twitching.
Closes #922
=> Bob deinterlacer correction
